//---------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Changes to this
//     file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generated on 2021 January 05 09:50:08 UTC
// </auto-generated>
//---------------------------------------------------------
using System;
using System.CodeDom.Compiler;
using System.Collections.Concurrent;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;


#nullable enable
#pragma warning disable CS0660, CS0661

namespace go
{
    public static partial class GodotGo_package
    {
        [GeneratedCode("go2cs", "0.1.0.0")]
        public partial interface IGetConfigurationWarning
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static IGetConfigurationWarning As<T>(in T target) => (IGetConfigurationWarning<T>)target!;

            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static IGetConfigurationWarning As<T>(ptr<T> target_ptr) => (IGetConfigurationWarning<T>)target_ptr;

            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static IGetConfigurationWarning? As(object target) =>
                typeof(IGetConfigurationWarning<>).CreateInterfaceHandler<IGetConfigurationWarning>(target);
        }

        [GeneratedCode("go2cs", "0.1.0.0")]
        public class IGetConfigurationWarning<T> : IGetConfigurationWarning
        {
            private T m_target = default!;
            private readonly ptr<T>? m_target_ptr;
            private readonly bool m_target_is_ptr;

            public ref T Target
            {
                get
                {
                    if (m_target_is_ptr && !(m_target_ptr is null))
                        return ref m_target_ptr.val;

                    return ref m_target;
                }
            }

            public IGetConfigurationWarning(in T target) => m_target = target;

            public IGetConfigurationWarning(ptr<T> target_ptr)
            {
                m_target_ptr = target_ptr;
                m_target_is_ptr = true;
            }

            private delegate @string _GetConfigurationWarningByPtr(ptr<T> value);
            private delegate @string _GetConfigurationWarningByVal(T value);

            private static readonly _GetConfigurationWarningByPtr? s__GetConfigurationWarningByPtr;
            private static readonly _GetConfigurationWarningByVal? s__GetConfigurationWarningByVal;

            [DebuggerNonUserCode, MethodImpl(MethodImplOptions.AggressiveInlining)]
            public @string _GetConfigurationWarning()
            {
                T target = m_target;

                if (m_target_is_ptr && !(m_target_ptr is null))
                    target = m_target_ptr.val;

                if (s__GetConfigurationWarningByPtr is null || !m_target_is_ptr)
                    return s__GetConfigurationWarningByVal!(target);

                return s__GetConfigurationWarningByPtr(m_target_ptr);
            }
            
            public string ToString(string? format, IFormatProvider? formatProvider) => format;

            [DebuggerStepperBoundary]
            static IGetConfigurationWarning()
            {
                Type targetType = typeof(T);
                Type targetTypeByPtr = typeof(ptr<T>);
                MethodInfo extensionMethod;

               extensionMethod = targetTypeByPtr.GetExtensionMethod("_GetConfigurationWarning");

                if (!(extensionMethod is null))
                    s__GetConfigurationWarningByPtr = extensionMethod.CreateStaticDelegate(typeof(_GetConfigurationWarningByPtr)) as _GetConfigurationWarningByPtr;

                extensionMethod = targetType.GetExtensionMethod("_GetConfigurationWarning");

                if (!(extensionMethod is null))
                    s__GetConfigurationWarningByVal = extensionMethod.CreateStaticDelegate(typeof(_GetConfigurationWarningByVal)) as _GetConfigurationWarningByVal;

                if (s__GetConfigurationWarningByPtr is null && s__GetConfigurationWarningByVal is null)
                    throw new NotImplementedException($"{targetType.FullName} does not implement IGetConfigurationWarning._GetConfigurationWarning method", new Exception("_GetConfigurationWarning"));
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static explicit operator IGetConfigurationWarning<T>(in ptr<T> target_ptr) => new IGetConfigurationWarning<T>(target_ptr);

            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static explicit operator IGetConfigurationWarning<T>(in T target) => new IGetConfigurationWarning<T>(target);

            // Enable comparisons between nil and IGetConfigurationWarning<T> interface instance
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(IGetConfigurationWarning<T> value, NilType nil) => Activator.CreateInstance<IGetConfigurationWarning<T>>().Equals(value);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(IGetConfigurationWarning<T> value, NilType nil) => !(value == nil);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(NilType nil, IGetConfigurationWarning<T> value) => value == nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(NilType nil, IGetConfigurationWarning<T> value) => value != nil;
        }
    }
}

namespace go
{
    public static class GodotGo_IGetConfigurationWarningExtensions
    {
        private static readonly ConcurrentDictionary<Type, MethodInfo> s_conversionOperators = new ConcurrentDictionary<Type, MethodInfo>();

        [GeneratedCode("go2cs", "0.1.0.0"), MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
        public static T _<T>(this go.GodotGo_package.IGetConfigurationWarning target)
        {
            try
            {
                return ((go.GodotGo_package.IGetConfigurationWarning<T>)target).Target;
            }
            catch (NotImplementedException ex)
            {
                throw new PanicException($"interface conversion: {GetGoTypeName(target.GetType())} is not {GetGoTypeName(typeof(T))}: missing method {ex.InnerException?.Message}");
            }
        }

        [GeneratedCode("go2cs", "0.1.0.0"), MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
        public static bool _<T>(this go.GodotGo_package.IGetConfigurationWarning target, out T result)
        {
            try
            {
                result = target._<T>();
                return true;
            }
            catch (PanicException)
            {
                result = default!;
                return false;
            }
        }

        [GeneratedCode("go2cs", "0.1.0.0"), MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
        public static object? _(this go.GodotGo_package.IGetConfigurationWarning target, Type type)
        {
            try
            {
                MethodInfo? conversionOperator = s_conversionOperators.GetOrAdd(type, _ => typeof(go.GodotGo_package.IGetConfigurationWarning<>).GetExplicitGenericConversionOperator(type));

                if (conversionOperator is null)
                    throw new PanicException($"interface conversion: failed to create converter for {GetGoTypeName(target.GetType())} to {GetGoTypeName(type)}");

                dynamic? result = conversionOperator.Invoke(null, new object[] { target });
                return result?.Target;
            }
            catch (NotImplementedException ex)
            {
                throw new PanicException($"interface conversion: {GetGoTypeName(target.GetType())} is not {GetGoTypeName(type)}: missing method {ex.InnerException?.Message}");
            }
        }

        [GeneratedCode("go2cs", "0.1.0.0"), MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
        public static bool _(this go.GodotGo_package.IGetConfigurationWarning target, Type type, out object? result)
        {
            try
            {
                result = target._(type);
                return true;
            }
            catch (PanicException)
            {
                result = type.IsValueType ? Activator.CreateInstance(type) : null;
                return false;
            }
        }
    }
}