//---------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Changes to this
//     file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generated on 2021 January 05 09:50:08 UTC
// </auto-generated>
//---------------------------------------------------------
using System;
using System.CodeDom.Compiler;
using System.Collections.Concurrent;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;


#nullable enable
#pragma warning disable CS0660, CS0661

namespace go
{
    public static partial class GodotGo_package
    {
        [GeneratedCode("go2cs", "0.1.0.0")]
        public partial interface IExitTree
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static IExitTree As<T>(in T target) => (IExitTree<T>)target!;

            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static IExitTree As<T>(ptr<T> target_ptr) => (IExitTree<T>)target_ptr;

            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static IExitTree? As(object target) =>
                typeof(IExitTree<>).CreateInterfaceHandler<IExitTree>(target);
        }

        [GeneratedCode("go2cs", "0.1.0.0")]
        public class IExitTree<T> : IExitTree
        {
            private T m_target = default!;
            private readonly ptr<T>? m_target_ptr;
            private readonly bool m_target_is_ptr;

            public ref T Target
            {
                get
                {
                    if (m_target_is_ptr && !(m_target_ptr is null))
                        return ref m_target_ptr.val;

                    return ref m_target;
                }
            }

            public IExitTree(in T target) => m_target = target;

            public IExitTree(ptr<T> target_ptr)
            {
                m_target_ptr = target_ptr;
                m_target_is_ptr = true;
            }

            private delegate void _ExitTreeByPtr(ptr<T> value);
            private delegate void _ExitTreeByVal(T value);

            private static readonly _ExitTreeByPtr? s__ExitTreeByPtr;
            private static readonly _ExitTreeByVal? s__ExitTreeByVal;

            [DebuggerNonUserCode, MethodImpl(MethodImplOptions.AggressiveInlining)]
            public void _ExitTree()
            {
                T target = m_target;

                if (m_target_is_ptr && !(m_target_ptr is null))
                    target = m_target_ptr.val;

                if (s__ExitTreeByPtr is null || !m_target_is_ptr)
                {
                    s__ExitTreeByVal!(target);
                    return;
                }

                s__ExitTreeByPtr(m_target_ptr);
                return;
                
            }
            
            public string ToString(string? format, IFormatProvider? formatProvider) => format;

            [DebuggerStepperBoundary]
            static IExitTree()
            {
                Type targetType = typeof(T);
                Type targetTypeByPtr = typeof(ptr<T>);
                MethodInfo extensionMethod;

               extensionMethod = targetTypeByPtr.GetExtensionMethod("_ExitTree");

                if (!(extensionMethod is null))
                    s__ExitTreeByPtr = extensionMethod.CreateStaticDelegate(typeof(_ExitTreeByPtr)) as _ExitTreeByPtr;

                extensionMethod = targetType.GetExtensionMethod("_ExitTree");

                if (!(extensionMethod is null))
                    s__ExitTreeByVal = extensionMethod.CreateStaticDelegate(typeof(_ExitTreeByVal)) as _ExitTreeByVal;

                if (s__ExitTreeByPtr is null && s__ExitTreeByVal is null)
                    throw new NotImplementedException($"{targetType.FullName} does not implement IExitTree._ExitTree method", new Exception("_ExitTree"));
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static explicit operator IExitTree<T>(in ptr<T> target_ptr) => new IExitTree<T>(target_ptr);

            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static explicit operator IExitTree<T>(in T target) => new IExitTree<T>(target);

            // Enable comparisons between nil and IExitTree<T> interface instance
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(IExitTree<T> value, NilType nil) => Activator.CreateInstance<IExitTree<T>>().Equals(value);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(IExitTree<T> value, NilType nil) => !(value == nil);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(NilType nil, IExitTree<T> value) => value == nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(NilType nil, IExitTree<T> value) => value != nil;
        }
    }
}

namespace go
{
    public static class GodotGo_IExitTreeExtensions
    {
        private static readonly ConcurrentDictionary<Type, MethodInfo> s_conversionOperators = new ConcurrentDictionary<Type, MethodInfo>();

        [GeneratedCode("go2cs", "0.1.0.0"), MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
        public static T _<T>(this go.GodotGo_package.IExitTree target)
        {
            try
            {
                return ((go.GodotGo_package.IExitTree<T>)target).Target;
            }
            catch (NotImplementedException ex)
            {
                throw new PanicException($"interface conversion: {GetGoTypeName(target.GetType())} is not {GetGoTypeName(typeof(T))}: missing method {ex.InnerException?.Message}");
            }
        }

        [GeneratedCode("go2cs", "0.1.0.0"), MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
        public static bool _<T>(this go.GodotGo_package.IExitTree target, out T result)
        {
            try
            {
                result = target._<T>();
                return true;
            }
            catch (PanicException)
            {
                result = default!;
                return false;
            }
        }

        [GeneratedCode("go2cs", "0.1.0.0"), MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
        public static object? _(this go.GodotGo_package.IExitTree target, Type type)
        {
            try
            {
                MethodInfo? conversionOperator = s_conversionOperators.GetOrAdd(type, _ => typeof(go.GodotGo_package.IExitTree<>).GetExplicitGenericConversionOperator(type));

                if (conversionOperator is null)
                    throw new PanicException($"interface conversion: failed to create converter for {GetGoTypeName(target.GetType())} to {GetGoTypeName(type)}");

                dynamic? result = conversionOperator.Invoke(null, new object[] { target });
                return result?.Target;
            }
            catch (NotImplementedException ex)
            {
                throw new PanicException($"interface conversion: {GetGoTypeName(target.GetType())} is not {GetGoTypeName(type)}: missing method {ex.InnerException?.Message}");
            }
        }

        [GeneratedCode("go2cs", "0.1.0.0"), MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
        public static bool _(this go.GodotGo_package.IExitTree target, Type type, out object? result)
        {
            try
            {
                result = target._(type);
                return true;
            }
            catch (PanicException)
            {
                result = type.IsValueType ? Activator.CreateInstance(type) : null;
                return false;
            }
        }
    }
}