//---------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Changes to this
//     file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generated on 2021 January 05 09:50:08 UTC
// </auto-generated>
//---------------------------------------------------------
using System;
using System.CodeDom.Compiler;
using System.Collections.Concurrent;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;


#nullable enable
#pragma warning disable CS0660, CS0661

namespace go
{
    public static partial class GodotGo_package
    {
        [GeneratedCode("go2cs", "0.1.0.0")]
        public partial interface IUnhandledKeyInput
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static IUnhandledKeyInput As<T>(in T target) => (IUnhandledKeyInput<T>)target!;

            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static IUnhandledKeyInput As<T>(ptr<T> target_ptr) => (IUnhandledKeyInput<T>)target_ptr;

            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static IUnhandledKeyInput? As(object target) =>
                typeof(IUnhandledKeyInput<>).CreateInterfaceHandler<IUnhandledKeyInput>(target);
        }

        [GeneratedCode("go2cs", "0.1.0.0")]
        public class IUnhandledKeyInput<T> : IUnhandledKeyInput
        {
            private T m_target = default!;
            private readonly ptr<T>? m_target_ptr;
            private readonly bool m_target_is_ptr;

            public ref T Target
            {
                get
                {
                    if (m_target_is_ptr && !(m_target_ptr is null))
                        return ref m_target_ptr.val;

                    return ref m_target;
                }
            }

            public IUnhandledKeyInput(in T target) => m_target = target;

            public IUnhandledKeyInput(ptr<T> target_ptr)
            {
                m_target_ptr = target_ptr;
                m_target_is_ptr = true;
            }

            private delegate void _UnhandledKeyInputByPtr(ptr<T> value, InputEventKey @event);
            private delegate void _UnhandledKeyInputByVal(T value, InputEventKey @event);

            private static readonly _UnhandledKeyInputByPtr? s__UnhandledKeyInputByPtr;
            private static readonly _UnhandledKeyInputByVal? s__UnhandledKeyInputByVal;

            [DebuggerNonUserCode, MethodImpl(MethodImplOptions.AggressiveInlining)]
            public void _UnhandledKeyInput(InputEventKey @event)
            {
                T target = m_target;

                if (m_target_is_ptr && !(m_target_ptr is null))
                    target = m_target_ptr.val;

                if (s__UnhandledKeyInputByPtr is null || !m_target_is_ptr)
                {
                    s__UnhandledKeyInputByVal!(target, @event);
                    return;
                }

                s__UnhandledKeyInputByPtr(m_target_ptr, @event);
                return;
                
            }
            
            public string ToString(string? format, IFormatProvider? formatProvider) => format;

            [DebuggerStepperBoundary]
            static IUnhandledKeyInput()
            {
                Type targetType = typeof(T);
                Type targetTypeByPtr = typeof(ptr<T>);
                MethodInfo extensionMethod;

               extensionMethod = targetTypeByPtr.GetExtensionMethod("_UnhandledKeyInput");

                if (!(extensionMethod is null))
                    s__UnhandledKeyInputByPtr = extensionMethod.CreateStaticDelegate(typeof(_UnhandledKeyInputByPtr)) as _UnhandledKeyInputByPtr;

                extensionMethod = targetType.GetExtensionMethod("_UnhandledKeyInput");

                if (!(extensionMethod is null))
                    s__UnhandledKeyInputByVal = extensionMethod.CreateStaticDelegate(typeof(_UnhandledKeyInputByVal)) as _UnhandledKeyInputByVal;

                if (s__UnhandledKeyInputByPtr is null && s__UnhandledKeyInputByVal is null)
                    throw new NotImplementedException($"{targetType.FullName} does not implement IUnhandledKeyInput._UnhandledKeyInput method", new Exception("_UnhandledKeyInput"));
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static explicit operator IUnhandledKeyInput<T>(in ptr<T> target_ptr) => new IUnhandledKeyInput<T>(target_ptr);

            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static explicit operator IUnhandledKeyInput<T>(in T target) => new IUnhandledKeyInput<T>(target);

            // Enable comparisons between nil and IUnhandledKeyInput<T> interface instance
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(IUnhandledKeyInput<T> value, NilType nil) => Activator.CreateInstance<IUnhandledKeyInput<T>>().Equals(value);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(IUnhandledKeyInput<T> value, NilType nil) => !(value == nil);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(NilType nil, IUnhandledKeyInput<T> value) => value == nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(NilType nil, IUnhandledKeyInput<T> value) => value != nil;
        }
    }
}

namespace go
{
    public static class GodotGo_IUnhandledKeyInputExtensions
    {
        private static readonly ConcurrentDictionary<Type, MethodInfo> s_conversionOperators = new ConcurrentDictionary<Type, MethodInfo>();

        [GeneratedCode("go2cs", "0.1.0.0"), MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
        public static T _<T>(this go.GodotGo_package.IUnhandledKeyInput target)
        {
            try
            {
                return ((go.GodotGo_package.IUnhandledKeyInput<T>)target).Target;
            }
            catch (NotImplementedException ex)
            {
                throw new PanicException($"interface conversion: {GetGoTypeName(target.GetType())} is not {GetGoTypeName(typeof(T))}: missing method {ex.InnerException?.Message}");
            }
        }

        [GeneratedCode("go2cs", "0.1.0.0"), MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
        public static bool _<T>(this go.GodotGo_package.IUnhandledKeyInput target, out T result)
        {
            try
            {
                result = target._<T>();
                return true;
            }
            catch (PanicException)
            {
                result = default!;
                return false;
            }
        }

        [GeneratedCode("go2cs", "0.1.0.0"), MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
        public static object? _(this go.GodotGo_package.IUnhandledKeyInput target, Type type)
        {
            try
            {
                MethodInfo? conversionOperator = s_conversionOperators.GetOrAdd(type, _ => typeof(go.GodotGo_package.IUnhandledKeyInput<>).GetExplicitGenericConversionOperator(type));

                if (conversionOperator is null)
                    throw new PanicException($"interface conversion: failed to create converter for {GetGoTypeName(target.GetType())} to {GetGoTypeName(type)}");

                dynamic? result = conversionOperator.Invoke(null, new object[] { target });
                return result?.Target;
            }
            catch (NotImplementedException ex)
            {
                throw new PanicException($"interface conversion: {GetGoTypeName(target.GetType())} is not {GetGoTypeName(type)}: missing method {ex.InnerException?.Message}");
            }
        }

        [GeneratedCode("go2cs", "0.1.0.0"), MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
        public static bool _(this go.GodotGo_package.IUnhandledKeyInput target, Type type, out object? result)
        {
            try
            {
                result = target._(type);
                return true;
            }
            catch (PanicException)
            {
                result = type.IsValueType ? Activator.CreateInstance(type) : null;
                return false;
            }
        }
    }
}