//---------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Changes to this
//     file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generated on 2021 January 05 09:50:08 UTC
// </auto-generated>
//---------------------------------------------------------
using System;
using System.CodeDom.Compiler;
using System.Collections.Concurrent;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;


#nullable enable
#pragma warning disable CS0660, CS0661

namespace go
{
    public static partial class GodotGo_package
    {
        [GeneratedCode("go2cs", "0.1.0.0")]
        public partial interface IPhysicsProcess
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static IPhysicsProcess As<T>(in T target) => (IPhysicsProcess<T>)target!;

            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static IPhysicsProcess As<T>(ptr<T> target_ptr) => (IPhysicsProcess<T>)target_ptr;

            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static IPhysicsProcess? As(object target) =>
                typeof(IPhysicsProcess<>).CreateInterfaceHandler<IPhysicsProcess>(target);
        }

        [GeneratedCode("go2cs", "0.1.0.0")]
        public class IPhysicsProcess<T> : IPhysicsProcess
        {
            private T m_target = default!;
            private readonly ptr<T>? m_target_ptr;
            private readonly bool m_target_is_ptr;

            public ref T Target
            {
                get
                {
                    if (m_target_is_ptr && !(m_target_ptr is null))
                        return ref m_target_ptr.val;

                    return ref m_target;
                }
            }

            public IPhysicsProcess(in T target) => m_target = target;

            public IPhysicsProcess(ptr<T> target_ptr)
            {
                m_target_ptr = target_ptr;
                m_target_is_ptr = true;
            }

            private delegate void _PhysicsProcessByPtr(ptr<T> value, float delta);
            private delegate void _PhysicsProcessByVal(T value, float delta);

            private static readonly _PhysicsProcessByPtr? s__PhysicsProcessByPtr;
            private static readonly _PhysicsProcessByVal? s__PhysicsProcessByVal;

            [DebuggerNonUserCode, MethodImpl(MethodImplOptions.AggressiveInlining)]
            public void _PhysicsProcess(float delta)
            {
                T target = m_target;

                if (m_target_is_ptr && !(m_target_ptr is null))
                    target = m_target_ptr.val;

                if (s__PhysicsProcessByPtr is null || !m_target_is_ptr)
                {
                    s__PhysicsProcessByVal!(target, delta);
                    return;
                }

                s__PhysicsProcessByPtr(m_target_ptr, delta);
                return;
                
            }
            
            public string ToString(string? format, IFormatProvider? formatProvider) => format;

            [DebuggerStepperBoundary]
            static IPhysicsProcess()
            {
                Type targetType = typeof(T);
                Type targetTypeByPtr = typeof(ptr<T>);
                MethodInfo extensionMethod;

               extensionMethod = targetTypeByPtr.GetExtensionMethod("_PhysicsProcess");

                if (!(extensionMethod is null))
                    s__PhysicsProcessByPtr = extensionMethod.CreateStaticDelegate(typeof(_PhysicsProcessByPtr)) as _PhysicsProcessByPtr;

                extensionMethod = targetType.GetExtensionMethod("_PhysicsProcess");

                if (!(extensionMethod is null))
                    s__PhysicsProcessByVal = extensionMethod.CreateStaticDelegate(typeof(_PhysicsProcessByVal)) as _PhysicsProcessByVal;

                if (s__PhysicsProcessByPtr is null && s__PhysicsProcessByVal is null)
                    throw new NotImplementedException($"{targetType.FullName} does not implement IPhysicsProcess._PhysicsProcess method", new Exception("_PhysicsProcess"));
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static explicit operator IPhysicsProcess<T>(in ptr<T> target_ptr) => new IPhysicsProcess<T>(target_ptr);

            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static explicit operator IPhysicsProcess<T>(in T target) => new IPhysicsProcess<T>(target);

            // Enable comparisons between nil and IPhysicsProcess<T> interface instance
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(IPhysicsProcess<T> value, NilType nil) => Activator.CreateInstance<IPhysicsProcess<T>>().Equals(value);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(IPhysicsProcess<T> value, NilType nil) => !(value == nil);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(NilType nil, IPhysicsProcess<T> value) => value == nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(NilType nil, IPhysicsProcess<T> value) => value != nil;
        }
    }
}

namespace go
{
    public static class GodotGo_IPhysicsProcessExtensions
    {
        private static readonly ConcurrentDictionary<Type, MethodInfo> s_conversionOperators = new ConcurrentDictionary<Type, MethodInfo>();

        [GeneratedCode("go2cs", "0.1.0.0"), MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
        public static T _<T>(this go.GodotGo_package.IPhysicsProcess target)
        {
            try
            {
                return ((go.GodotGo_package.IPhysicsProcess<T>)target).Target;
            }
            catch (NotImplementedException ex)
            {
                throw new PanicException($"interface conversion: {GetGoTypeName(target.GetType())} is not {GetGoTypeName(typeof(T))}: missing method {ex.InnerException?.Message}");
            }
        }

        [GeneratedCode("go2cs", "0.1.0.0"), MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
        public static bool _<T>(this go.GodotGo_package.IPhysicsProcess target, out T result)
        {
            try
            {
                result = target._<T>();
                return true;
            }
            catch (PanicException)
            {
                result = default!;
                return false;
            }
        }

        [GeneratedCode("go2cs", "0.1.0.0"), MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
        public static object? _(this go.GodotGo_package.IPhysicsProcess target, Type type)
        {
            try
            {
                MethodInfo? conversionOperator = s_conversionOperators.GetOrAdd(type, _ => typeof(go.GodotGo_package.IPhysicsProcess<>).GetExplicitGenericConversionOperator(type));

                if (conversionOperator is null)
                    throw new PanicException($"interface conversion: failed to create converter for {GetGoTypeName(target.GetType())} to {GetGoTypeName(type)}");

                dynamic? result = conversionOperator.Invoke(null, new object[] { target });
                return result?.Target;
            }
            catch (NotImplementedException ex)
            {
                throw new PanicException($"interface conversion: {GetGoTypeName(target.GetType())} is not {GetGoTypeName(type)}: missing method {ex.InnerException?.Message}");
            }
        }

        [GeneratedCode("go2cs", "0.1.0.0"), MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
        public static bool _(this go.GodotGo_package.IPhysicsProcess target, Type type, out object? result)
        {
            try
            {
                result = target._(type);
                return true;
            }
            catch (PanicException)
            {
                result = type.IsValueType ? Activator.CreateInstance(type) : null;
                return false;
            }
        }
    }
}