//---------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Changes to this
//     file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generated on 2021 January 05 09:50:08 UTC
// </auto-generated>
//---------------------------------------------------------
using System;
using System.CodeDom.Compiler;
using System.Collections.Concurrent;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;


#nullable enable
#pragma warning disable CS0660, CS0661

namespace go
{
    public static partial class GodotGo_package
    {
        [GeneratedCode("go2cs", "0.1.0.0")]
        public partial interface IUnhandledInput
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static IUnhandledInput As<T>(in T target) => (IUnhandledInput<T>)target!;

            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static IUnhandledInput As<T>(ptr<T> target_ptr) => (IUnhandledInput<T>)target_ptr;

            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static IUnhandledInput? As(object target) =>
                typeof(IUnhandledInput<>).CreateInterfaceHandler<IUnhandledInput>(target);
        }

        [GeneratedCode("go2cs", "0.1.0.0")]
        public class IUnhandledInput<T> : IUnhandledInput
        {
            private T m_target = default!;
            private readonly ptr<T>? m_target_ptr;
            private readonly bool m_target_is_ptr;

            public ref T Target
            {
                get
                {
                    if (m_target_is_ptr && !(m_target_ptr is null))
                        return ref m_target_ptr.val;

                    return ref m_target;
                }
            }

            public IUnhandledInput(in T target) => m_target = target;

            public IUnhandledInput(ptr<T> target_ptr)
            {
                m_target_ptr = target_ptr;
                m_target_is_ptr = true;
            }

            private delegate void _UnhandledInputByPtr(ptr<T> value, InputEvent @event);
            private delegate void _UnhandledInputByVal(T value, InputEvent @event);

            private static readonly _UnhandledInputByPtr? s__UnhandledInputByPtr;
            private static readonly _UnhandledInputByVal? s__UnhandledInputByVal;

            [DebuggerNonUserCode, MethodImpl(MethodImplOptions.AggressiveInlining)]
            public void _UnhandledInput(InputEvent @event)
            {
                T target = m_target;

                if (m_target_is_ptr && !(m_target_ptr is null))
                    target = m_target_ptr.val;

                if (s__UnhandledInputByPtr is null || !m_target_is_ptr)
                {
                    s__UnhandledInputByVal!(target, @event);
                    return;
                }

                s__UnhandledInputByPtr(m_target_ptr, @event);
                return;
                
            }
            
            public string ToString(string? format, IFormatProvider? formatProvider) => format;

            [DebuggerStepperBoundary]
            static IUnhandledInput()
            {
                Type targetType = typeof(T);
                Type targetTypeByPtr = typeof(ptr<T>);
                MethodInfo extensionMethod;

               extensionMethod = targetTypeByPtr.GetExtensionMethod("_UnhandledInput");

                if (!(extensionMethod is null))
                    s__UnhandledInputByPtr = extensionMethod.CreateStaticDelegate(typeof(_UnhandledInputByPtr)) as _UnhandledInputByPtr;

                extensionMethod = targetType.GetExtensionMethod("_UnhandledInput");

                if (!(extensionMethod is null))
                    s__UnhandledInputByVal = extensionMethod.CreateStaticDelegate(typeof(_UnhandledInputByVal)) as _UnhandledInputByVal;

                if (s__UnhandledInputByPtr is null && s__UnhandledInputByVal is null)
                    throw new NotImplementedException($"{targetType.FullName} does not implement IUnhandledInput._UnhandledInput method", new Exception("_UnhandledInput"));
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static explicit operator IUnhandledInput<T>(in ptr<T> target_ptr) => new IUnhandledInput<T>(target_ptr);

            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static explicit operator IUnhandledInput<T>(in T target) => new IUnhandledInput<T>(target);

            // Enable comparisons between nil and IUnhandledInput<T> interface instance
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(IUnhandledInput<T> value, NilType nil) => Activator.CreateInstance<IUnhandledInput<T>>().Equals(value);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(IUnhandledInput<T> value, NilType nil) => !(value == nil);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(NilType nil, IUnhandledInput<T> value) => value == nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(NilType nil, IUnhandledInput<T> value) => value != nil;
        }
    }
}

namespace go
{
    public static class GodotGo_IUnhandledInputExtensions
    {
        private static readonly ConcurrentDictionary<Type, MethodInfo> s_conversionOperators = new ConcurrentDictionary<Type, MethodInfo>();

        [GeneratedCode("go2cs", "0.1.0.0"), MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
        public static T _<T>(this go.GodotGo_package.IUnhandledInput target)
        {
            try
            {
                return ((go.GodotGo_package.IUnhandledInput<T>)target).Target;
            }
            catch (NotImplementedException ex)
            {
                throw new PanicException($"interface conversion: {GetGoTypeName(target.GetType())} is not {GetGoTypeName(typeof(T))}: missing method {ex.InnerException?.Message}");
            }
        }

        [GeneratedCode("go2cs", "0.1.0.0"), MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
        public static bool _<T>(this go.GodotGo_package.IUnhandledInput target, out T result)
        {
            try
            {
                result = target._<T>();
                return true;
            }
            catch (PanicException)
            {
                result = default!;
                return false;
            }
        }

        [GeneratedCode("go2cs", "0.1.0.0"), MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
        public static object? _(this go.GodotGo_package.IUnhandledInput target, Type type)
        {
            try
            {
                MethodInfo? conversionOperator = s_conversionOperators.GetOrAdd(type, _ => typeof(go.GodotGo_package.IUnhandledInput<>).GetExplicitGenericConversionOperator(type));

                if (conversionOperator is null)
                    throw new PanicException($"interface conversion: failed to create converter for {GetGoTypeName(target.GetType())} to {GetGoTypeName(type)}");

                dynamic? result = conversionOperator.Invoke(null, new object[] { target });
                return result?.Target;
            }
            catch (NotImplementedException ex)
            {
                throw new PanicException($"interface conversion: {GetGoTypeName(target.GetType())} is not {GetGoTypeName(type)}: missing method {ex.InnerException?.Message}");
            }
        }

        [GeneratedCode("go2cs", "0.1.0.0"), MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
        public static bool _(this go.GodotGo_package.IUnhandledInput target, Type type, out object? result)
        {
            try
            {
                result = target._(type);
                return true;
            }
            catch (PanicException)
            {
                result = type.IsValueType ? Activator.CreateInstance(type) : null;
                return false;
            }
        }
    }
}