//---------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Changes to this
//     file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generated on 2021 January 05 09:00:48 UTC
// </auto-generated>
//---------------------------------------------------------
using Godot;
using System;
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using static go.builtin;
using fmt = go.fmt_package;

//#nullable enable

namespace go
{
    public static partial class GodotGo_package
    {
        [GeneratedCode("go2cs", "0.1.0.0")]
        public partial struct LineFollow3D
        {
            // Constructors
            public LineFollow3D(NilType _)
            {
                this.parent = default;
                this.points = default;
                this.doLoop = default;
                this.cube = default;
                this.speed = default;
                this.currentDistance = default;
                this.lineDistances = default;
            }

            public LineFollow3D(Node parent = default, slice<Vector3> points = default, bool doLoop = default, CSGBox cube = default, float speed = default, float currentDistance = default, slice<float> lineDistances = default)
            {
                this.parent = parent;
                this.points = points;
                this.doLoop = doLoop;
                this.cube = cube;
                this.speed = speed;
                this.currentDistance = currentDistance;
                this.lineDistances = lineDistances;
            }

            // Enable comparisons between nil and LineFollow3D struct
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(LineFollow3D value, NilType nil) => value.Equals(default(LineFollow3D));

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(LineFollow3D value, NilType nil) => !(value == nil);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(NilType nil, LineFollow3D value) => value == nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(NilType nil, LineFollow3D value) => value != nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static implicit operator LineFollow3D(NilType nil) => default(LineFollow3D);
        }

        //[GeneratedCode("go2cs", "0.1.0.0")]
        //public static LineFollow3D LineFollow3D_cast(dynamic value)
        //{
        //    return new LineFollow3D(value.parent, value.points, value.doLoop, value.cube, value.speed, value.currentDistance, value.lineDistances);
        //}
    }
}